### PR TITLE
C51-428: Update CiviCase Extension Readme

### PR DESCRIPTION
**Pull request by tunbola**
## Overview
In line with the work to prep CiviCase for the Community, this PR updates the readme for the extension.

View the updated changes [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/83ffbb626645a7f5947ed39f90a2220adbf5e79f/README.md)

### CODE REVIEW

**Comment by mi-kon** [comment]
@tunbola I think we should be more specific reg CiviCRM and Shoreditch versions to use

**Comment by tunbola** [comment]
@mi-kon , Stating specific version is a bit tricky, for example, latest shoreditch needs v5.12 or Civi v5.8 with another extension. 
Most likely we will have Civicase releases supporting specific version of Civicrm and there might not be a one version fits all.

I think we can do Civicrm  >= v5.8
Shoreditch >= v0.1-alpha35

**Comment by mi-kon** [comment]
@tunbola i think either mininal version or the tested version should suffice.

**Comment by tunbola** [comment]
@mi-kon , Discussed with Jerry. Will leave as below:
Civicrm >= v5.8 
Shoreditch >= v0.1-alpha32

**Pull request merged**
