### PR TITLE
Remove unnecessary DisplayAllCustomGroupsInCaseForm build Form hook

### PR DESCRIPTION
**Pull request by agileware-justin**
Remove unnecessary DisplayAllCustomGroupsInCaseForm build Form hook.

Its function is covered by core (at least in 5.42), and all it seems to do is add a duplicate of the case custom fields in the activity custom fields section of the case create form.

## Before

A validation error for a case which has custom fields would cause a duplication of those custom fields as shown in the screenshot below. You can see the custom fieldset "Test" is repeated.

Screenshot_20211014_090706

## After

No duplication of custom fields.

## Technical Details

Function is covered by core (at least in 5.42), and all it seems to do is add a duplicate of the case custom fields in the activity custom fields section of the case create form.

## Comments

Agileware Ref: CIVICRM-1867

### CODE REVIEW

**Comment by agileware-justin** [comment]
@mlutfy you might be interested in this fix too

**Comment by olayiwola-compucorp** [comment]
Thanks 🙏 for the PR @agileware-justin, would it be possible you resolve the merge conflicts

**Comment by agileware-justin** [comment]
Thanks was a PITA @olayiwola-compucorp but done now.

**Comment by olayiwola-compucorp** [comment]
Thanks, @agileware-justin , looks like the failing test is not caused by this PR. I will merge this into the workstream branch and fix the failing test before sending it to QA.

thanks

**Review by olayiwola-compucorp — APPROVED** [review]

**Pull request merged**
