### PR TITLE
Update Angular loading for 5.37

### LINKED ISSUE #752: Latest CiviCase (1.14.0) Breaks Activities Tab in Contact Summary
After upgrading both CiviCase (to 1.14.0) and Core (to 5.35.1), when we go to a specific Contact record and click on Activities, nothing shows up even though there are activities. If I disable CiviCase, activities show up (in the old table listing format/style). My dev console shows the following error with CiviCase is enabled and I refresh the Activities page:

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.8.0/$injector/modulerr?p0=civicaseActivitiesTab&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.8.0%2F%24injector%2Fmodulerr%3Fp0%3Dcivicase%26p1%3D%255B%2524injector%253Aunpr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.8.0%252F%2524injector%252Funpr%253Fp0%253DActivityFormsProvider%250AF%252F%253C%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A7%253A168%250Afb%252Fp.%2524injector%253C%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A46%253A468%250Ad%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A44%253A197%250Ae%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fa…
    Angular 7
    jQuery 9
    refresh crm.ajax.js:303
    jQuery 8
    refresh crm.ajax.js:284
    jQuery 5
    loadPage crm.ajax.js:372
    <anonymous> TabHeader.js:52
    jQuery 38
    <anonymous> TabHeader.js:56
    jQuery 8
angular.js:99

```

### PR DESCRIPTION
**Pull request by colemanw**
## Overview
This fixes Angular module loading to play nice with other modules, as multiple Angular apps may coexist on the page.

## Before
Multiple Angular modules on the page would interfere with each other. A simple way to reproduce:

1. Enable the `afform` & `afform_admin` extensions.
2. Go to *Form Builder*, add a new form and click the "Add to Contact Summary Page" checkbox. Save.
3. The new form will appear on the contact summary page, but the CiviCase tabs are now broken (no content appears in them).

## After
Conflicts resolved.

## Technical Details
Uses the new `angularjs.loader` service, from CiviCRM v5.37.
See https://github.com/civicrm/civicrm-core/pull/19922

## Comments
I believe this fixes #752

### CODE REVIEW

**Comment by tunbola** [comment]
@colemanw , Thanks for this! Unable to replicate this yet because Civicase has only been tested on Civi 5.35 for now, but we'll take note of this and add a ticket in when it eventually gets tested on 5.37. 

cc @james-compucorp

**Comment by mlutfy** [comment]
I have encountered this on CiviCRM 5.40 (soon to be RC) and can confirm that the patch works for me.

**Comment by pbarmak** [comment]
I can confirm the patch fixes #752 and it looks like it also fixes #813. I can now upgrade Civi Core to 5.40.4 and all seems to be working so far. It would be great to have this merged into master at some point.

Just fyi for those that might see this comment: I did notice that the branch for this does seem to require another extension (uk.co.compucorp.usermenu); install that extension in order to avoid errors.

**Comment by colemanw** [comment]
@james-compucorp @jamienovick the recent security release in CiviCRM is forcing people to upgrade past 5.35 - it would be really good to get this merged!

**Comment by jamienovick** [comment]
Hi @colemanw we've used the CKEditor v5 extension on our stack and so unfortunately I don't think this will be updated till the following Civi security release as it stands, but we guarantee it will be reviewed / merged as soon as that takes place. If we can get ahead of that I'll let you know.

**Pull request merged**
