### PR TITLE
CPS-130: Show 'Case details' field

### PR DESCRIPTION
**Pull request by ivan-compucorp**
## Overview
The **Case details** field was missing on *Manage cases* page and on *Cases* tab of *Contact details* page. This PR adds case details field on those pages and makes it editable on click.

## Before / After
Manage cases before:
image

Manage cases after:
image

Contact details - Cases tab before:
image

Contact details - Cases tab after:
image

Manage cases - details field placeholder:
image

Contact details - details field placeholder:
image

## Technical Details
1. To print field on pages mentioned we had to update respective templates.
2. On _Manage cases_ page:
- padding was added to the _Last updated_ field to align it's left border and make it match the left border of _Subject_ and _Details_ field.
- top margin was added here to separate fields (margin was copied from _Subject_ field).
3. On _Contact details_ page:
- bottom margin was added to the _Details_ field to separate it from _Type_ field (margin was copied from _Subject_ field).
- also we set height (see min-height) to the textareas of _Subject_ and _Details_ fields, because initially textarea of _Subject_ field was bigger, but it should be visa versa (just common sense).
- we removed `.pull-left` class from fields container, because textarea width was just half-width because of it. After some investigation I found no reasons of using this class here (it's just a small container without siblings), so I decided to remove this class instead of setting 100% width to this container.
4. Also small formatting fix was made in templates.

### CODE REVIEW

**Comment by jamienovick** [comment]
@ivan-compucorp 
How does this look without any case details now?

**Comment by ivan-compucorp** [comment]
@jamienovick added screenshots with placeholders, check please.

**Comment by deb1990** [comment]
@ivan-compucorp What if the description is too long, will it break the layout? In terms of height. Will it come out of the white area in Case Details?

**Comment by ivan-compucorp** [comment]
It looks fine: 
image

**Comment by jamienovick** [comment]
@fran-compucorp @shitijg Just pointing out that whilst this is not "broken" it's not going to be an acceptable UX solution for a long description and we will need a suitable way to not display the full text at the top if it's long. Thanks

**Pull request merged**
