### PR TITLE
NEUSPRT-239: Sort activities Tag list in alphabetical order

### PR DESCRIPTION
**Pull request by olayiwola-compucorp**
## Overview
This PR sorts the activities Tag list in alphabetical order.

## Before
The tag list was sorted by ID
beforeneu

## After
The tag list is sorted by name in Ascending order.
afterneu

### CODE REVIEW

**Comment by olayiwola-compucorp** [comment]
I don't think so @jamienovick 

This is what the tag create screen looks like.

Screenshot 2023-06-20 at 10 41 26

**Comment by jamienovick** [comment]
See my video added to ticket (couldn't upload here for some reason). Is there a sort order field? @olayiwola-compucorp

**Comment by olayiwola-compucorp** [comment]
Great @jamienovick , there's no `sort order` field, below is a sample response from the Tags GET API.

```json
        {
            "id": "16",
            "name": "Apple",
            "is_selectable": "1",
            "is_reserved": "0",
            "is_tagset": "0",
            "used_for": "civicrm_activity",
            "created_id": "2",
            "color": "#2fc15b",
            "created_date": "2023-06-20 09:09:44"
        },
        {
            "id": "17",
            "name": "Ball",
            "is_selectable": "1",
            "is_reserved": "0",
            "is_tagset": "0",
            "used_for": "civicrm_activity",
            "created_id": "2",
            "color": "#188991",
            "created_date": "2023-06-20 09:10:10"
        },
        {
            "id": "18",
            "name": "Cat",
            "is_selectable": "1",
            "is_reserved": "0",
            "is_tagset": "0",
            "used_for": "civicrm_activity",
            "created_id": "2",
            "color": "#d81313",
            "created_date": "2023-06-20 09:10:20"
        },
        {
            "id": "19",
            "name": "Dog",
            "is_selectable": "1",
            "is_reserved": "0",
            "is_tagset": "0",
            "used_for": "civicrm_activity",
            "created_id": "2",
            "color": "#a39714",
            "created_date": "2023-06-20 09:10:34"
        },
        {
            "id": "20",
            "name": "Elephant",
            "is_selectable": "1",
            "is_reserved": "0",
            "is_tagset": "0",
            "used_for": "civicrm_activity",
            "created_id": "2",
            "color": "#6c5151",
            "created_date": "2023-06-20 09:10:52"
        },
        {
            "id": "21",
            "name": "Axe",
            "is_selectable": "1",
            "is_reserved": "0",
            "is_tagset": "0",
            "used_for": "civicrm_activity",
            "created_id": "2",
            "color": "#207708",
            "created_date": "2023-06-20 10:13:07"
        }
```

**Comment by jamienovick** [comment]
Got it, sounds like alphabetical is the best we have @olayiwola-compucorp

**Review by omarabuhussein — APPROVED** [review]

**Pull request merged**
