### PR TITLE
Translation function for strings update ts > E::ts()

### PR DESCRIPTION
**Pull request by UshaMakoa**
## Overview
Translation strings update (to add more in transifex)

## Before
code uses ts() function

## After
code uses E::ts() function

## Comments
There is still a pb when civistring retrieve and compile the .mo from transifex but you can update your .mo manually.

### CODE REVIEW

**Comment by reneolivo** [comment]
@UshaMakoa thanks a lot for this.

What's the difference between using `E::ts` versus `ts` (which is globally available) ? Can you please add more details in the PR?

Also, if we go with this approach we should use a different variable name than `E`. I know this is the value used by default by CiviCRM, but it can be confused with an error constant, etc. `Utils::ts`  would be prefered, or similar.

**Comment by eileenmcnaughton** [comment]
@reneolivo E::ts is supported by civix as the preferred method because it is supported in the transifex flow. The strings uploaded for ts() are those that are part of the core code base

The alternative is to alter all existing calls to ts() to add in the extension name 

https://github.com/totten/civix/pull/98

**Comment by mlutfy** [comment]
I have not tested, but at a glance, +1  on using `E::ts`, otherwise localization is not possible.

However, the PR might require more testing. Each file should have this statement at the top:

```
use CRM_Civicase_ExtensionUtil as E;
```

**Comment by tunbola** [comment]
Thanks @mlutfy for the PR. We are going to add this to the backlog and do this in a more detailed way in PHP files, Angular template files and smarty files in the civicase extension. We'll be updating this issue with updates on how the work is going and the next targeted release version of civicase this will go into.

**Comment by tunbola** [comment]
Closing this as this should be done in a more detailed way. We'll add a ticket for this and add an update on the next targeted release version of civicase this will likely go into.

**Comment by samuelsov** [comment]
@tunbola can we have a status on this ?
I plan to work on a PR to fix the all the ts but if you have made any progress on this, it would avoid some double work.
A link to the new ticket could help.
Thanks!

**Comment by tunbola** [comment]
@samuelsov , This is being worked on at the moment and should be released soon.

**Pull request closed without merging**
